'use client';

import { useState, useMemo } from 'react';
import sharedStyles from '@/styles/shared-tool-styles.module.css';

const SAMPLE_SVG = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Vector Graphic Software v1.2 -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve">
  <metadata>
    <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <rdf:Work rdf:about="">
        <dc:format>image/svg+xml</dc:format>
      </rdf:Work>
    </rdf:RDF>
  </metadata>
  <g id="Layer_1">
    <circle cx="50.000" cy="50.000" r="40.000" fill="#2196F3" stroke="#000000" stroke-width="2.000"/>
  </g>
</svg>`;

function optimizeSvgCode(
  svg: string,
  options: { removeComments: boolean; removeMetadata: boolean; removeDoctype: boolean; minifyWhitespace: boolean }
): string {
  let res = svg;

  if (options.removeDoctype) {
    res = res.replace(/<\?xml[^>]*\?>/gi, '').replace(/<!DOCTYPE[^>]*>/gi, '');
  }
  if (options.removeComments) {
    res = res.replace(/<!--[\s\S]*?-->/g, '');
  }
  if (options.removeMetadata) {
    res = res.replace(/<metadata[\s\S]*?<\/metadata>/gi, '');
  }

  // Strip redundant attributes (e.g. enable-background, x="0px", y="0px")
  res = res
    .replace(/\s*(enable-background|xml:space)="[^"]*"/gi, '')
    .replace(/\s*(x|y)="0(px)?"/gi, '');

  if (options.minifyWhitespace) {
    res = res.replace(/>\s+</g, '><').trim();
  }

  return res;
}

export default function SvgOptimizer() {
  const [svgInput, setSvgInput] = useState(SAMPLE_SVG);
  const [removeComments, setRemoveComments] = useState(true);
  const [removeMetadata, setRemoveMetadata] = useState(true);
  const [removeDoctype, setRemoveDoctype] = useState(true);
  const [minifyWhitespace, setMinifyWhitespace] = useState(true);
  const [copied, setCopied] = useState(false);

  const optimizedSvg = useMemo(() => {
    return optimizeSvgCode(svgInput, {
      removeComments,
      removeMetadata,
      removeDoctype,
      minifyWhitespace,
    });
  }, [svgInput, removeComments, removeMetadata, removeDoctype, minifyWhitespace]);

  const stats = useMemo(() => {
    const origSize = new TextEncoder().encode(svgInput).length;
    const optSize = new TextEncoder().encode(optimizedSvg).length;
    const saved = origSize - optSize;
    const ratio = origSize > 0 ? ((saved / origSize) * 100).toFixed(1) : '0';
    return { origSize, optSize, saved, ratio };
  }, [svgInput, optimizedSvg]);

  const handleCopy = () => {
    navigator.clipboard.writeText(optimizedSvg);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([optimizedSvg], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'optimized.svg';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ maxWidth: 1100 }}>
      <section className={sharedStyles.section}>
        <div className={sharedStyles.card}>
          <div style={{ display: 'flex', gap: 16, marginBottom: 16, flexWrap: 'wrap', fontSize: '0.875rem' }}>
            <label style={{ display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={removeComments}
                onChange={(e) => setRemoveComments(e.target.checked)}
              />
              Remove Comments
            </label>
            <label style={{ display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={removeMetadata}
                onChange={(e) => setRemoveMetadata(e.target.checked)}
              />
              Remove XML Metadata
            </label>
            <label style={{ display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={removeDoctype}
                onChange={(e) => setRemoveDoctype(e.target.checked)}
              />
              Remove XML Header & Doctype
            </label>
            <label style={{ display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={minifyWhitespace}
                onChange={(e) => setMinifyWhitespace(e.target.checked)}
              />
              Minify Whitespace
            </label>
          </div>

          {/* Stats bar */}
          <div
            style={{
              padding: 12,
              borderRadius: 6,
              background: 'rgba(76, 175, 80, 0.1)',
              border: '1px solid rgba(76, 175, 80, 0.3)',
              marginBottom: 20,
              display: 'flex',
              gap: 20,
              alignItems: 'center',
              fontSize: '0.9rem',
            }}
          >
            <div>Original: <strong>{stats.origSize} bytes</strong></div>
            <div>Optimized: <strong>{stats.optSize} bytes</strong></div>
            <div style={{ color: '#4caf50', fontWeight: 'bold' }}>
              Saved: {stats.saved} bytes ({stats.ratio}%)
            </div>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
            <div className={sharedStyles.field}>
              <label className={sharedStyles.fieldLabel} htmlFor="svgInput">
                Raw SVG Code Input
              </label>
              <textarea
                id="svgInput"
                value={svgInput}
                onChange={(e) => setSvgInput(e.target.value)}
                className={sharedStyles.textarea}
                rows={12}
                style={{ fontFamily: 'monospace', fontSize: '0.85rem' }}
              />
            </div>

            <div className={sharedStyles.field}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
                <label className={sharedStyles.fieldLabel} htmlFor="svgOptOutput">
                  Optimized SVG Code
                </label>
                <div style={{ display: 'flex', gap: 8 }}>
                  <button type="button" className={sharedStyles.button} onClick={handleCopy}>
                    {copied ? 'Copied!' : 'Copy SVG'}
                  </button>
                  <button type="button" className={`${sharedStyles.button} ${sharedStyles.buttonPrimary}`} onClick={handleDownload}>
                    Download
                  </button>
                </div>
              </div>
              <textarea
                id="svgOptOutput"
                readOnly
                value={optimizedSvg}
                className={sharedStyles.outputArea}
                rows={12}
                style={{ fontFamily: 'monospace', fontSize: '0.85rem' }}
              />
            </div>
          </div>

          {/* SVG Preview Card */}
          <div style={{ marginTop: 24 }}>
            <h4 style={{ marginBottom: 12 }}>Visual SVG Preview</h4>
            <div
              style={{
                padding: 24,
                borderRadius: 8,
                background: 'rgba(0, 0, 0, 0.3)',
                border: '1px dashed var(--border-color, #444)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                minHeight: 120,
              }}
              dangerouslySetInnerHTML={{ __html: optimizedSvg }}
            />
          </div>
        </div>
      </section>
    </div>
  );
}
