let loadedImage = null;
let faviconData = {};

const dropZone = document.getElementById("dropZone");
dropZone.addEventListener("dragover", (e) => {
	e.preventDefault();
	dropZone.style.background = "var(--color-background-secondary)";
});
dropZone.addEventListener("dragleave", () => {
	dropZone.style.background = "";
});
dropZone.addEventListener("drop", (e) => {
	e.preventDefault();
	dropZone.style.background = "";
	if (e.dataTransfer.files[0]) handleFile(e.dataTransfer.files[0]);
});

document.getElementById("themeColor").addEventListener("input", function () {
	document.getElementById("themeColorHex").value = this.value;
});

function syncColorFromText() {
	const val = document.getElementById("themeColorHex").value;
	if (/^#[0-9a-fA-F]{6}$/.test(val)) document.getElementById("themeColor").value = val;
}

function handleFile(file) {
	if (!file) return;
	const reader = new FileReader();
	reader.onload = (e) => {
		const img = new Image();
		img.onload = () => {
			loadedImage = img;
			document.getElementById("imgName").textContent = file.name;
			document.getElementById("imgDims").textContent = img.width + " × " + img.height + "px";
			renderPreviews(img);
			document.getElementById("dropContent").style.display = "none";
			document.getElementById("previewContent").style.display = "block";
			dropZone.classList.add("has-image");
		};
		img.src = e.target.result;
	};
	reader.readAsDataURL(file);
}

function renderPreviews(img) {
	[
		["prev16", 16],
		["prev32", 32],
		["prev64", 64],
		["prev180", 60],
		["prev192", 48],
	].forEach(([id, size]) => {
		const c = document.getElementById(id);
		const ctx = c.getContext("2d");
		ctx.clearRect(0, 0, size, size);
		ctx.drawImage(img, 0, 0, size, size);
	});
}

function clearImage(e) {
	e.stopPropagation();
	loadedImage = null;
	faviconData = {};
	document.getElementById("dropContent").style.display = "block";
	document.getElementById("previewContent").style.display = "none";
	dropZone.classList.remove("has-image");
	document.getElementById("imgInput").value = "";
}

function getResized(img, size) {
	const c = document.getElementById("workCanvas");
	c.width = size;
	c.height = size;
	const ctx = c.getContext("2d");
	ctx.clearRect(0, 0, size, size);
	ctx.drawImage(img, 0, 0, size, size);
	return c.toDataURL("image/png");
}

function generateAll() {
	const name = document.getElementById("siteName").value.trim() || "My Site";
	const url = (document.getElementById("siteUrl").value.trim() || "https://example.com").replace(/\/$/, "");
	const desc = document.getElementById("siteDesc").value.trim() || "";
	const theme = document.getElementById("themeColor").value || "#1a1a1a";
	const ogType = document.getElementById("ogType").value;
	const lang = document.getElementById("htmlLang").value;
	const kw = document.getElementById("keywords").value.trim();

	let f16 = "",
		f32 = "",
		f180 = "",
		f192 = "",
		f512 = "";
	if (loadedImage) {
		f16 = getResized(loadedImage, 16);
		f32 = getResized(loadedImage, 32);
		f180 = getResized(loadedImage, 180);
		f192 = getResized(loadedImage, 192);
		f512 = getResized(loadedImage, 512);
	}

	const faviconLines = loadedImage
		? `
  <!-- Favicons -->
  <link rel="icon" type="image/png" sizes="16x16" href="${f16}">
  <link rel="icon" type="image/png" sizes="32x32" href="${f32}">
  <link rel="apple-touch-icon" sizes="180x180" href="${f180}">
  <link rel="icon" type="image/png" sizes="192x192" href="${f192}">
  <link rel="icon" type="image/png" sizes="512x512" href="${f512}">
  <link rel="shortcut icon" href="${f32}">`
		: `
  <!-- Favicons (add your favicon files) -->
  <link rel="icon" type="image/png" sizes="16x16" href="favicons/favicon-16x16.png">
  <link rel="icon" type="image/png" sizes="32x32" href="favicons/favicon-32x32.png">
  <link rel="apple-touch-icon" sizes="180x180" href="favicons/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="192x192" href="favicons/android-chrome-192x192.png">
  <link rel="icon" type="image/png" sizes="512x512" href="favicons/android-chrome-512x512.png">
  <link rel="shortcut icon" href="favicons/favicon.ico">`;

	const ogImage = loadedImage ? f512 : `${url}/og-image.png`;

	const code = `<!-- ═══════════════════════════════════════════ -->
<!-- Generated by Favicon & Meta Generator      -->
<!-- ═══════════════════════════════════════════ -->

<!-- Charset & Viewport -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<!-- Primary Meta Tags -->
<title>${name}</title>
<meta name="title" content="${name}">
${desc ? `<meta name="description" content="${esc(desc)}">` : ""}
${kw ? `<meta name="keywords" content="${esc(kw)}">` : ""}
<meta name="author" content="${name}">
<meta name="robots" content="index, follow">
<meta name="language" content="${lang}">
<meta name="theme-color" content="${theme}">
<link rel="canonical" href="${url}/">
${faviconLines}

  <!-- Web Manifest -->
  <link rel="manifest" href="site.webmanifest">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="${ogType}">
<meta property="og:url" content="${url}/">
<meta property="og:title" content="${name}">
${desc ? `<meta property="og:description" content="${esc(desc)}">` : ""}
<meta property="og:image" content="${ogImage}">
<meta property="og:image:width" content="512">
<meta property="og:image:height" content="512">
<meta property="og:site_name" content="${name}">
<meta property="og:locale" content="${lang}_${lang.toUpperCase()}">

<!-- Twitter Card -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:url" content="${url}/">
<meta name="twitter:title" content="${name}">
${desc ? `<meta name="twitter:description" content="${esc(desc)}">` : ""}
<meta name="twitter:image" content="${ogImage}">

<!-- Schema.org / Structured Data -->
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "WebSite",
  "name": "${name}",
  "url": "${url}/",
  "description": "${esc(desc || name)}"
}
<\/script>

<!-- PWA / Mobile -->
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="default">
<meta name="apple-mobile-web-app-title" content="${name}">
<meta name="msapplication-TileColor" content="${theme}">
<meta name="msapplication-config" content="browserconfig.xml">`;

	document.getElementById("outputCode").textContent = code;
	document.getElementById("outputSection").style.display = "block";

	const badges = document.getElementById("outputBadges");
	badges.innerHTML = "";
	const items = [
		["Primary meta", "success"],
		["Open Graph", "success"],
		["Twitter Card", "success"],
		["Schema.org", "info"],
		["PWA tags", "info"],
		loadedImage ? ["Favicons (base64)", "success"] : ["Favicon placeholders", "info"],
		["Canonical URL", "success"],
	];
	items.forEach(([t, cls]) => {
		const b = document.createElement("span");
		b.className = `badge badge-${cls}`;
		b.style.marginRight = "4px";
		b.textContent = t;
		badges.appendChild(b);
	});

	document.getElementById("outputSection").scrollIntoView({ behavior: "smooth", block: "start" });
}

function esc(s) {
	return s.replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function copyCode() {
	const code = document.getElementById("outputCode").textContent;
	navigator.clipboard.writeText(code).then(() => {
		const btn = event.target;
		btn.textContent = "Copied!";
		setTimeout(() => (btn.textContent = "Copy code"), 2000);
	});
}

function downloadZip() {
	if (!loadedImage) {
		alert("Upload an image first to download favicon files.");
		return;
	}
	const sizes = [
		[16, "favicon-16x16"],
		[32, "favicon-32x32"],
		[180, "apple-touch-icon"],
		[192, "android-chrome-192x192"],
		[512, "android-chrome-512x512"],
	];
	sizes.forEach(([size, name]) => {
		const url = getResized(loadedImage, size);
		const a = document.createElement("a");
		a.href = url;
		a.download = name + ".png";
		a.click();
	});

	const manifest = JSON.stringify(
		{
			name: document.getElementById("siteName").value || "My Site",
			short_name: (document.getElementById("siteName").value || "Site").split(" ")[0],
			icons: [
				{ src: "/favicons/android-chrome-192x192.png", sizes: "192x192", type: "image/png" },
				{ src: "/favicons/android-chrome-512x512.png", sizes: "512x512", type: "image/png" },
			],
			theme_color: document.getElementById("themeColor").value,
			background_color: "#ffffff",
			display: "standalone",
		},
		null,
		2,
	);
	const mBlob = new Blob([manifest], { type: "application/json" });
	const mA = document.createElement("a");
	mA.href = URL.createObjectURL(mBlob);
	mA.download = "site.webmanifest";
	mA.click();
}

// ── Subtle cursor glow follow on tool cards ───────────────────────────────

function initCursorGlow() {
	const glow = document.createElement("div");
	glow.className = "cursor-glow";
	document.body.appendChild(glow);
	let fadeTimeout;
	document.addEventListener("mousemove", (event) => {
		glow.style.left = `${event.clientX}px`;
		glow.style.top = `${event.clientY}px`;
		glow.style.opacity = "1";
		glow.style.zIndex = "0";
		clearTimeout(fadeTimeout);
		fadeTimeout = setTimeout(() => {
			glow.style.opacity = "0";
		}, 900);
	});
	document.addEventListener("mouseleave", () => {
		glow.style.opacity = "0";
	});
}
initCursorGlow();
